# docker-compose version
version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: xxl-mq-mysql
    environment:
      # 1、数据库密码设置，需要与Admin中配置一致：
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # 2、数据库实例名称，需要与Admin中配置一致；
      MYSQL_DATABASE: xxl_mq
    ports:
      - "3306:3306"
    volumes:
      # 说明：仅数据库首次初始化时执行；
      - ../doc/db/tables_xxl_mq.sql:/docker-entrypoint-initdb.d/tables_xxl_mq.sql:ro
      # 3、数据库持久化目录位置，建议自定义：
      - ${MYSQL_PATH}/conf:/etc/mysql/conf.d
      - ${MYSQL_PATH}/logs:/var/log/mysql
      - ${MYSQL_PATH}/data:/var/lib/mysql
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - xxl-mq-network

  xxl-mq-admin:
    # 4、本地Build设置，如果期望使用推动DockerHub的镜像，可以注释当前启用的image、build配置，并启用如下设置版本的image配置；
    #image: xuxueli/xxl-mq-admin:{version}
    image: xuxueli/xxl-mq-admin:local
    build:
      context: ../xxl-mq-admin
      dockerfile: Dockerfile
    container_name: xxl-mq-admin
    environment:
      # 5、数据库密码设置，需要与上文Mysql中保持一致：
      PARAMS: >-
        --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_mq?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        --spring.datasource.username=root 
        --spring.datasource.password=${MYSQL_ROOT_PASSWORD}
        --server.port=${XXL_MQ_ADMIN_PORT}
        --server.servlet.context-path=${XXL_MQ_ADMIN_CONTEXT_PATH}
    ports:
      - "${XXL_MQ_ADMIN_PORT}:${XXL_MQ_ADMIN_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - xxl-mq-network

  xxl-mq-samples-springboot:
    image: xuxueli/xxl-mq-samples-springboot:local
    build:
      context: ../xxl-mq-samples/xxl-mq-samples-springboot
      dockerfile: Dockerfile
    container_name: xxl-mq-samples-springboot
    environment:
      PARAMS: >-
        --xxl.mq.admin.address=http://xxl-mq-admin:${XXL_MQ_ADMIN_PORT}${XXL_MQ_ADMIN_CONTEXT_PATH:-/}
    ports:
      - "8081:8081"
    depends_on:
      xxl-mq-admin:
        condition: service_started
    networks:
      - xxl-mq-network

networks:
  xxl-mq-network:
    driver: bridge
